trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  PYTHON_SCRIPT: 'scripts/automate_terraform.py'
  INPUT_CSV: 'acr.csv'   # Replace with the name of your input CSV file

steps:
# Step 1: Checkout code
- checkout: self
  displayName: 'Checkout source code'

# Step 2: Install Python
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
  displayName: 'Set up Python'

- script: |
    python3 -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Python dependencies'

# Step 3: Install Terraform
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
  displayName: 'Install Terraform'

# Step 4: Initialize Terraform
- script: terraform --version
  displayName: 'Verify Terraform installation'

# Step 5: Prepare the environment and execute Python script
- script: |
    python3 $(PYTHON_SCRIPT) $(INPUT_CSV)
  displayName: 'Run Python script'

# Optional: Add cleanup tasks
- script: |
    echo "Cleaning up workspace"
  displayName: 'Cleanup workspace'
