trigger: none

pool:
  name: default
  demands:
    - agent.name -equals VICTOR

variables:
  OUTPUT_FOLDER: "tfvars"
  INPUT_CSV: "csv/acr.csv"

jobs:
  - job: GenerateMatrix
    displayName: "Generate tfvars files and dynamic matrix"
    steps:
      - checkout: self
        displayName: "Checkout source code"

      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.x"
          addToPath: true
        displayName: "Set up Python"

      - script: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
        displayName: "Install Python dependencies"

      - script: |
          python scripts/parse_csv.py $(INPUT_CSV) $(OUTPUT_FOLDER)
        displayName: "Generate tfvars files from CSV"

      - script: |
          python scripts/generate_matrix.py > matrix_output.txt
          for /f "delims=" %%A in (matrix_output.txt) do set MATRIX=%%A
          echo ##vso[task.setvariable variable=TFVARS_MATRIX;isOutput=true]%MATRIX%
        displayName: "Generate dynamic matrix"

  - job: ProcessTerraform
    displayName: "Process Terraform Workspaces"
    dependsOn: GenerateMatrix
    strategy:
      matrix: $[ dependencies.GenerateMatrix.outputs['TFVARS_MATRIX'] ]
    steps:
      - checkout: self
        displayName: "Checkout source code"

      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'Azure subscription 1(6e47c803-d4a0-49b2-9b1f-01500ce57b80)'
          backendAzureRmResourceGroupName: 'my-rg'
          backendAzureRmStorageAccountName: 'bondastorage'
          backendAzureRmContainerName: 'terrformstatecontainer'
          backendAzureRmKey: '$(TFVARS_FILE).tfstate'

      - script: |
          terraform workspace new $(TFVARS_FILE) || terraform workspace select $(TFVARS_FILE)
          terraform plan -var-file=$(OUTPUT_FOLDER)/$(TFVARS_FILE)
          terraform apply -var-file=$(OUTPUT_FOLDER)/$(TFVARS_FILE) -auto-approve
        displayName: "Run Terraform Plan and Apply"
